version: "3.9"

services:

  api:
    container_name: "temperature_api"
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "80:80"
    expose:
      - 80
    entrypoint: ["uvicorn", "src.main:api", "--proxy-headers", "--host", "0.0.0.0", "--port", "80"]